
version: 2

models:
  - name: products_clean
    description: "Product data"
    columns:
      - name: product_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: name
        description: "product name"
        data_tests:
          - not_null
      - name: category
        description: "product category"
        data_tests:
          - not_null
      - name: price
        description: "product price"
        data_tests:
          - not_null

  - name: daily_sales
    description: "sales granulated by day"
